package plugdb

import (
	"fmt"

	"github.com/cozy/cozy-stack/pkg/plugdb"
	"github.com/labstack/echo"
)

// HelloWorld says hello
func HelloWorld(c echo.Context) error {
	fmt.Println("hello world plugdb")

	x := plugdb.Random()
	fmt.Printf("random generated by C : %v\n", x)

	return nil
}

// Routes sets the routing for the sharing service
func Routes(router *echo.Group) {
	router.GET("/", HelloWorld)
	router.GET("", HelloWorld)
}
